# Generated by Django 2.0.6 on 2018-08-08 21:06

import charsheet.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='alignment_good_axis',
            field=models.CharField(choices=[('GOOD', 'Good'), ('NEUTRAL', 'Neutral'), ('EVIL', 'Evil')], default=charsheet.constants.AlignmentGoodAxis('Neutral'), max_length=8),
        ),
        migrations.AddField(
            model_name='character',
            name='alignment_law_axis',
            field=models.CharField(choices=[('LAWFUL', 'Lawful'), ('TRUE', 'True'), ('CHAOTIC', 'Chaotic')], default=charsheet.constants.AlignmentLawAxis('True'), max_length=8),
        ),
        migrations.AddField(
            model_name='character',
            name='deity',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='character',
            name='eyes',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default=charsheet.constants.Gender('Male'), max_length=8),
        ),
        migrations.AddField(
            model_name='character',
            name='hair',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='height',
            field=models.PositiveIntegerField(default=0, help_text='expressed in inches'),
        ),
        migrations.AddField(
            model_name='character',
            name='homeland',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='character',
            name='player',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='character',
            name='size',
            field=models.CharField(choices=[('FINE', 'Fine'), ('DIMINUTIVE', 'Diminutive'), ('TINY', 'Tiny'), ('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large'), ('HUGE', 'Huge'), ('GARGANTUAN', 'Gargantuan'), ('COLOSSAL', 'Colossal')], default=charsheet.constants.Size('Medium'), max_length=16),
        ),
        migrations.AddField(
            model_name='character',
            name='weight',
            field=models.PositiveIntegerField(default=0, help_text='expressed in pounds'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
