# Generated by Django 2.0.6 on 2018-08-10 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0004_auto_20180810_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bonus',
            old_name='type',
            new_name='bonus_type',
        ),
    ]
