# Generated by Django 2.0.6 on 2018-08-10 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0005_auto_20180810_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('requirements', models.CharField(max_length=256)),
                ('hit_die', models.PositiveIntegerField()),
                ('starting_wealth', models.CharField(max_length=32)),
                ('skill_ranks', models.PositiveIntegerField()),
                ('base_attack_progression', models.CharField(max_length=32)),
                ('good_fortitude_progression', models.BooleanField()),
                ('good_reflex_progression', models.BooleanField()),
                ('good_will_progression', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('key_ability', models.CharField(max_length=16)),
                ('trained_only', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='characterclass',
            name='class_skills',
            field=models.ManyToManyField(to='charsheet.Skill'),
        ),
    ]
