# Generated by Django 2.0.6 on 2018-08-10 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0006_auto_20180811_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('size', models.CharField(choices=[('FINE', 'Fine'), ('DIMINUTIVE', 'Diminutive'), ('TINY', 'Tiny'), ('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large'), ('HUGE', 'Huge'), ('GARGANTUAN', 'Gargantuan'), ('COLOSSAL', 'Colossal')], default='MEDIUM', max_length=16)),
                ('base_speed', models.PositiveIntegerField(help_text='expressed in feet')),
            ],
        ),
        migrations.AlterModelOptions(
            name='characterclass',
            options={'verbose_name_plural': 'CharacterClasses'},
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='charsheet.Race'),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='requirements',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='starting_wealth',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
