# Generated by Django 2.0.6 on 2018-08-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0007_auto_20180811_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='minimum',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='value',
            field=models.CharField(default='1', max_length=32),
        ),
    ]
