# Generated by Django 2.0.6 on 2018-08-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0013_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='value',
            field=models.CharField(default='', max_length=32),
        ),
    ]
