# Generated by Django 2.0.6 on 2018-08-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0014_auto_20180819_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterclass',
            name='is_prestige_class',
            field=models.BooleanField(default=False),
        ),
    ]
