# Generated by Django 2.0.6 on 2018-08-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0016_immunity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='immunity',
            options={'verbose_name_plural': 'Immunities'},
        ),
        migrations.AddField(
            model_name='immunity',
            name='source',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='immunity',
            name='source_type',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
