# Generated by Django 2.0.6 on 2018-08-19 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0017_auto_20180820_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionalModifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=32)),
                ('value', models.CharField(default='', max_length=32)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charsheet.Character')),
            ],
        ),
    ]
