# Generated by Django 2.0.6 on 2018-08-20 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0019_auto_20180820_0122'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='characterclasslevel',
            unique_together={('character', 'character_level')},
        ),
    ]
