# Generated by Django 2.0.6 on 2018-08-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0020_auto_20180820_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterclass',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
