# Generated by Django 2.0.6 on 2018-08-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0021_auto_20180820_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
