# Generated by Django 2.0.6 on 2018-08-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0022_character_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='burrow_speed',
            field=models.PositiveIntegerField(default=0, help_text='expressed in feet'),
        ),
        migrations.AddField(
            model_name='race',
            name='fly_maneuverability',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='race',
            name='fly_speed',
            field=models.PositiveIntegerField(default=0, help_text='expressed in feet'),
        ),
        migrations.AddField(
            model_name='race',
            name='swim_speed',
            field=models.PositiveIntegerField(default=0, help_text='expressed in feet'),
        ),
    ]
