# Generated by Django 2.0.6 on 2018-08-21 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0025_speed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_level', models.PositiveIntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charsheet.Character')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charsheet.Skill')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='rank',
            unique_together={('to', 'character_level')},
        ),
    ]
