# Generated by Django 2.0.6 on 2018-08-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0027_classskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('secret', models.BooleanField(default=False)),
            ],
        ),
    ]
