# Generated by Django 2.0.6 on 2018-08-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0029_character_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='languages',
            field=models.ManyToManyField(to='charsheet.Language'),
        ),
    ]
