# Generated by Django 2.0.6 on 2018-08-22 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0030_auto_20180822_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
                ('note', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SpecificWeapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_category', models.CharField(max_length=32)),
                ('use_category', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('cost', models.PositiveIntegerField()),
                ('damage_dice', models.PositiveIntegerField()),
                ('damage_die_type', models.PositiveIntegerField()),
                ('critical_range', models.PositiveIntegerField(default=20)),
                ('critical_multiplier', models.PositiveIntegerField(default=2)),
                ('range', models.PositiveIntegerField(default=0)),
                ('ammunition_type', models.CharField(blank=True, default='', max_length=8, null=True)),
                ('weight', models.PositiveIntegerField()),
                ('damage_type', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='WeaponProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='character',
            name='languages',
            field=models.ManyToManyField(blank=True, to='charsheet.Language'),
        ),
        migrations.AlterField(
            model_name='characterclasslevel',
            name='character_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='charsheet.CharacterClass'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='properties',
            field=models.ManyToManyField(blank=True, to='charsheet.WeaponProperty'),
        ),
        migrations.AddField(
            model_name='specificweapon',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charsheet.Character'),
        ),
        migrations.AddField(
            model_name='specificweapon',
            name='weapon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charsheet.Weapon'),
        ),
        migrations.AddField(
            model_name='attack',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charsheet.Character'),
        ),
        migrations.AddField(
            model_name='attack',
            name='weapon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charsheet.SpecificWeapon'),
        ),
    ]
