# Generated by Django 2.0.6 on 2018-10-28 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0032_auto_20180823_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullAttack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='weapon',
            name='manufactured',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='weapon',
            name='natural',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='deity',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='character',
            name='eyes',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='character',
            name='hair',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='character',
            name='homeland',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='character',
            name='player',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='charsheet.Race'),
        ),
        migrations.AddField(
            model_name='fullattack',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charsheet.Character'),
        ),
        migrations.AddField(
            model_name='fullattack',
            name='weapons',
            field=models.ManyToManyField(blank=True, to='charsheet.SpecificWeapon'),
        ),
    ]
