# Generated by Django 2.0.6 on 2018-10-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0033_auto_20181028_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificweapon',
            name='ammunition',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='specificweapon',
            name='ranged',
            field=models.BooleanField(default=False),
        ),
    ]
